UniversityMS/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using UniversityMS.Manager;
using UniversityMS.Models;

namespace UniversityMS.Controllers
{
    public class AdminController : Controller
    {
        private AdminManager admin = new AdminManager();
        //Sirajuls code starts here
        [HttpGet]
        public ActionResult AssignCourseToTeacher()
        {
            ViewData["departments"] = new SelectList(admin.GetAllDepartment(), "DepartmentId", "DepartmentCode");
            return View();
        }

        [HttpPost]
        public JsonResult AssignCourseToTeacher(AssignCourse assignCourse)
        {
            string message = admin.AssignCourseToTeacher(assignCourse);
            return Json(message, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult ViewCourseAssign()
        {
            ViewData["departments"] = new SelectList(admin.GetAllDepartment(), "DepartmentId", "DepartmentCode");
            return View();
        }

        [HttpPost]
        public ActionResult ViewCourseAssign(int departmentId)
        {
            List<AssignCourse> assignCourses = admin.GetCoursesInformation(departmentId);
            return Json(assignCourses);
        }

        [HttpGet]
        public ActionResult AllocateClassroom()
        {
            ViewData["departments"] = new SelectList(admin.GetAllDepartment(), "DepartmentId", "DepartmentCode");
            ViewData["rooms"] = new SelectList(admin.GetAllRooms(), "RoomId", "RoomNo");
            ViewData["days"] = new SelectList(admin.GetAllDays(), "DayId", "DayName");
            return View();
        }

        [HttpPost]
        public ActionResult AllocateClassroom(AllocatedClassroom allocatedClassroom)
        {
            var message = admin.AllocateClassroom(allocatedClassroom);
            return Json(message,JsonRequestBehavior.AllowGet);
        }



        public ActionResult UpdateTeacherTakenCredit(double extraCredit, int teacherId)
        {
            var message = admin.UpdateTeacherTakenCredit(extraCredit,teacherId);
            return Json(message, JsonRequestBehavior.AllowGet);
        }


        public ActionResult GetTeacherByDepartment(int departmentId)
        {
            List<Teacher> teachers = admin.GetTeacherByDepartment(departmentId);
            SelectList teacherSelectList = new SelectList(teachers, "TeacherId", "TeacherName", 0);
            return Json(teacherSelectList, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetCourseByDepartment(int departmentId)
        {
            List<Course> courses = admin.GetCourseByDepartment(departmentId);
            SelectList coursSelectList = new SelectList(courses, "CourseId", "CourseCode", 0);
            return Json(coursSelectList, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetTeacherById(int teacherId)
        {
            Teacher teacher = admin.GetTeacherById(teacherId);
            return Json(teacher, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetCourseById(int courseId)
        {
            Course course = admin.GetCourseById(courseId);
            return Json(course, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult ViewSchedule()
        {
            ViewData["departments"] = new SelectList(admin.GetAllDepartment(), "DepartmentId", "DepartmentCode");
            return View();
        }

        [HttpPost]
        public ActionResult ViewSchedule(int departmentId)
        {
            List<Course> courses = admin.GetClassroomInformation(departmentId);
            return Json(courses,JsonRequestBehavior.AllowGet);
        }
        public JsonResult IsCourseTaken(int courseId)
        {
            return Json(!admin.IsCourseTaken(courseId), JsonRequestBehavior.AllowGet);
        }

        //public JsonResult IsRoomAvailable(int roomId, int dayId, string fromTime, string toTime)
        //{
        //    return Json(!admin.IsRoomAvailable(roomId,dayId,fromTime,toTime), JsonRequestBehavior.AllowGet);
        //}


        [HttpGet]
        public ActionResult UnassignCourses()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UnassignCourses(int code)
        {
            string message = admin.UnassignCourses(code);
            return Json(message,JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult UnallocateClassroom()
        {
            return View();
        }
        [HttpPost]
        public ActionResult UnallocateClassroom(int code)
        {
            string message = admin.UnallocateClassroom(code);
            return Json(message, JsonRequestBehavior.AllowGet);
        }
        //Sirajuls code starts here
	}
}

UniversityMS/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityMS.Manager;
using UniversityMS.Models;

namespace UniversityMS.Controllers
{
    public class CourseController : Controller
    {
        //Soikats code starts here 
        AdminManager admin = new AdminManager();
       
        [HttpGet]
        public ActionResult SaveCourse()
        {
            ViewData["departments"] = new SelectList(admin.GetAllDepartment(), "DepartmentId", "DepartmentCode");
            ViewData["semesters"] = new SelectList(admin.GetSemesters(), "SemesterId", "SemesterName");
            return View();
        }

        [HttpPost]
        public ActionResult SaveCourse(Course course)
        {
            var message = admin.SaveCourse(course);
            return Json(message,JsonRequestBehavior.AllowGet);
        }


        public JsonResult IsCourseCodeTaken(string courseCode)
        {
            return Json(!admin.IsCourseCodeTaken(courseCode), JsonRequestBehavior.AllowGet);
        }

        public JsonResult IsCourseNameTaken(string courseName)
        {
            return Json(!admin.IsCourseNameTaken(courseName), JsonRequestBehavior.AllowGet);
        }
        //Soikats code ends here
	}
}

UniversityMS/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using iTextSharp.text;
using iTextSharp.text.pdf;
using iTextSharp.tool.xml;
using iTextSharp.text.html.simpleparser;
using Rotativa;
using Rotativa.MVC;
using UniversityMS.Manager;
using UniversityMS.Models;
using Font = iTextSharp.text.Font;

namespace UniversityMS.Controllers
{
    public class StudentController : Controller
    {
        StudentManager studentManager = new StudentManager();
        AdminManager admin = new AdminManager();
        //Sirajuls code start here
        public ActionResult ViewStudentResult()
        {
            ViewData["students"] = new SelectList(studentManager.GetStudents(), "StudentId", "RegistrationCode");
            return View();
        }

        [HttpPost]
        [ActionName("ViewStudentResult")]
        public ActionResult CreatePdf(Student student)
        {
            Document pdfDoc = new Document(PageSize.A4, 25, 25, 25, 15);
            PdfWriter pdfWriter = PdfWriter.GetInstance(pdfDoc, Response.OutputStream);
            pdfDoc.Open();

            //Top Heading
            Chunk chunk = new Chunk("Your Result Report has been Generated", FontFactory.GetFont("Arial", 20, Font.BOLDITALIC, BaseColor.BLACK));
            pdfDoc.Add(chunk);

            //Horizontal Line
            Paragraph line = new Paragraph(new Chunk(new iTextSharp.text.pdf.draw.LineSeparator(0.0F, 100.0F, BaseColor.BLACK, Element.ALIGN_MIDDLE, 1)));
            pdfDoc.Add(line);

            //Table
            PdfPTable table = new PdfPTable(1);
            table.WidthPercentage = 100;
            //0=Left, 1=Centre, 2=Right
            table.HorizontalAlignment = 0;
            table.SpacingBefore = 20f;
            table.SpacingAfter = 30f;

            Student newStudent = studentManager.GetStudent(student.StudentId);
            //Cell no 2
            chunk = new Chunk("Reg no: "+newStudent.RegistrationCode+"\nName: "+newStudent.StudentName +" \nEmail: "+newStudent.StudentEmail+" \nDepartment: "+newStudent.Department.DepartmentName+"", FontFactory.GetFont("Arial", 15, Font.NORMAL, BaseColor.BLACK));
            PdfPCell cell = new PdfPCell();
            cell.Border = 0;
            cell.AddElement(chunk);
            table.AddCell(cell);

            //Add table to document
            pdfDoc.Add(table);

            //Horizontal Line
            line = new Paragraph(new Chunk(new iTextSharp.text.pdf.draw.LineSeparator(0.0F, 100.0F, BaseColor.BLACK, Element.ALIGN_LEFT, 1)));
            pdfDoc.Add(line);

            //Table
            table = new PdfPTable(3);
            table.WidthPercentage = 100;
            table.HorizontalAlignment = 0;
            table.SpacingBefore = 20f;
            table.SpacingAfter = 30f;

            //Cell



            List<Course> courses = studentManager.GetCourses(student.StudentId);

            cell = new PdfPCell();
            chunk = new Chunk("Course Code");
            chunk.Font.Color = BaseColor.WHITE;
            cell.AddElement(chunk);
            cell.BackgroundColor = new BaseColor(21,140,186);
            table.AddCell(cell);

            cell = new PdfPCell();
            chunk = new Chunk("Name");
            chunk.Font.Color = BaseColor.WHITE;
            cell.AddElement(chunk);
            cell.BackgroundColor = new BaseColor(21, 140, 186);
            table.AddCell(cell);

            cell = new PdfPCell();
            chunk = new Chunk("Grade");
            chunk.Font.Color = BaseColor.WHITE;
            cell.AddElement(chunk);
            cell.BackgroundColor = new BaseColor(21, 140, 186);
            table.AddCell(cell);

            foreach (Course aCourse in courses)
            {
                table.AddCell(aCourse.CourseCode);
                table.AddCell(aCourse.CourseName);
                table.AddCell(aCourse.Grade.GradeCode);
            }

            pdfDoc.Add(table);
            pdfWriter.CloseStream = false;
            pdfDoc.Close();
            Response.Buffer = true;
            Response.ContentType = "application/pdf";
            Response.AddHeader("content-disposition", "attachment;filename=Credit-Card-Report.pdf");
            Response.Cache.SetCacheability(HttpCacheability.NoCache);
            Response.Write(pdfDoc);
            Response.End();
            ViewData["students"] = new SelectList(studentManager.GetStudents(), "StudentId", "RegistrationCode");
            return View();
        }
        [HttpPost]
        public ActionResult GetStudentInfo(int studentId)
        {
            Student student = studentManager.GetStudent(studentId);
            TempData["student"] = student;
            return Json(student, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult GetCourses(int studentId)
        {
            List<Course> courses = studentManager.GetCourses(studentId);
            TempData["courses"] = courses;
            return Json(courses, JsonRequestBehavior.AllowGet);
        }
        //Sirajuls code start here

        //Soikats code starts here
        [HttpGet]
        public ActionResult EnrollStudent()
        {
            ViewData["students"] = new SelectList(studentManager.GetStudents(), "StudentId", "RegistrationCode");
            return View();
        }
        [HttpPost]
        public ActionResult EnrollStudent(EnrollStudent enrollStudent)
        {
            string message = studentManager.EnrollStudent(enrollStudent);
            return Json(message, JsonRequestBehavior.AllowGet);
        }
        //Soikats code ends here

        //Ujjwal Code starts here
        [HttpGet]
        public ActionResult RegisterStudent()
        {
            ViewData["departments"] = new SelectList(admin.GetAllDepartment(), "DepartmentId", "DepartmentCode");
            return View();
        }

        [HttpPost]
        public ActionResult RegisterStudent(Student student)
        {
            string message = studentManager.RegisterStudent(student);
            return Json(message,JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult SaveStudentResult()
        {
            ViewData["students"] = new SelectList(studentManager.GetStudents(), "StudentId", "RegistrationCode");
            ViewData["grades"] = new SelectList(studentManager.GetGradeList(), "GradeId", "GradeCode");
            return View();
        }
        
        [HttpPost]
        public ActionResult SaveStudentResult(StudentResult studentResult)
        {
            string message = studentManager.SaveStudentResult(studentResult);
            return Json(message,JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult UpdateStudentResult(StudentResult studentResult)
        {
            string message = studentManager.UpdateStudentResult(studentResult);
            return Json(message, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetCoursesByEnrollId(int studentId)
        {
            SelectList coursesList = new SelectList(studentManager.GetCoursesByEnrollId(studentId), "CourseId", "CourseCode");
            return Json(coursesList, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetCoursesByDepartmentlId(int studentId)
        {
            SelectList coursesList = new SelectList(studentManager.GetCoursesByDepartmentlId(studentId), "CourseId", "CourseCode");
            return Json(coursesList, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult GetStudentById(int studentId)
        {
            Student student = studentManager.GetStudentById(studentId);
            return Json(student, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public ActionResult IsResultAlreadyExists(int courseId, int studentId)
        {
            return Json(studentManager.IsResultAlreadyExists(courseId, studentId), JsonRequestBehavior.AllowGet);
        }

        public JsonResult IsCourseEnrolled(int courseId,int studentRegEId)
        {
            return Json(!studentManager.IsCourseEnrolled(courseId,studentRegEId), JsonRequestBehavior.AllowGet);
        }

        public JsonResult IsStudentEmailExists(string studentEmail)
        {
            return Json(!studentManager.IsStudentEmailExists(studentEmail), JsonRequestBehavior.AllowGet);
        }
        //Ujjwal Code ends here
    }
}

UniversityMS/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityMS.Manager;
using UniversityMS.Models;

namespace UniversityMS.Controllers
{
    public class TeacherController : Controller
    {
       
        AdminManager admin = new AdminManager();
        //Soikats code starts here
        public ActionResult SaveTeacher()
        {
            ViewData["designations"] = new SelectList(admin.GetDesignations(), "DesignationId", "DesignationName");
            ViewData["departments"] = new SelectList(admin.GetAllDepartment(), "DepartmentId", "DepartmentCode");
            return View();
        }

        [HttpPost]
        public ActionResult SaveTeacher(Teacher teacher)
        {
            var message = admin.SaveTeacher(teacher);
            return Json(message,JsonRequestBehavior.AllowGet);
        }

        public JsonResult IsTeacherEmailTaken(string teacherEmail)
        {
            return Json(!admin.IsTeacherEmailTaken(teacherEmail),JsonRequestBehavior.AllowGet);
        }
        //Soikats code ends here
	}
}

UniversityMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Content/jquery.timepicker.css" rel="stylesheet" />
    <link href="~/Content/Master.css" rel="stylesheet" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/themes/base/datepicker.css" rel="stylesheet" />
    <link href="~/Content/alertifyjs/alertify.min.css" rel="stylesheet" />
    <link href="~/Content/alertifyjs/themes/bootstrap.css" rel="stylesheet"/>
    <link rel="shortcut icon" href="#">
</head>
<body>
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="@Url.Action("Index", "Home")">UniversityMs</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Home")">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown" id="admin">
                    <a class="nav-link dropdown-toggle"  href="@Url.Action("Index", "Home")" role="button" aria-haspopup="true" aria-expanded="false">Admin</a>
                    <div class="dropdown-menu" id="adminDropdown">
                        <a class="dropdown-item" href="@Url.Action("SaveDepartment", "Department")">Create Department</a>
                        <a class="dropdown-item" href="@Url.Action("Index", "Department")">View Department</a>
                        <a class="dropdown-item" href="@Url.Action("SaveCourse", "Course")">Save Course</a>
                        <a class="dropdown-item" href="@Url.Action("SaveTeacher", "Teacher")">Save Teacher</a>
                        <a class="dropdown-item" href="@Url.Action("AssignCourseToTeacher", "Admin")">Assign Course</a>
                        <a class="dropdown-item" href="@Url.Action("ViewCourseAssign", "Admin")">View Course Assign</a>
                        <a class="dropdown-item" href="@Url.Action("AllocateClassroom", "Admin")">Allocate Classroom</a>
                        <a class="dropdown-item" href="@Url.Action("ViewSchedule", "Admin")">View Schedule</a>
                        
                        <a class="dropdown-item" href="@Url.Action("ViewStudentResult", "Student")">View Result</a>
                    </div>
                </li>
                <li class="nav-item dropdown" id="teacher">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Teacher</a>
                    <div class="dropdown-menu" id="teacherDropdown">
                        <a class="dropdown-item" href="@Url.Action("RegisterStudent", "Student")">Register Student</a>
                        <a class="dropdown-item" href="@Url.Action("EnrollStudent", "Student")">Enroll Course</a>
                    </div>
                </li>
                <li class="nav-item dropdown" id="student">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Student</a>
                    <div class="dropdown-menu" id="studentDropdown">
                        <a class="dropdown-item" href="@Url.Action("SaveStudentResult", "Student")">Save Student Result</a>
                    </div>
                </li>
                <li class="nav-item dropdown" id="reset">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Reset</a>
                    <div class="dropdown-menu" id="resetDropdown">
                        <a class="dropdown-item" href="@Url.Action("UnassignCourses", "Admin")">Unassign Courses</a>
                        <a class="dropdown-item" href="@Url.Action("UnallocateClassroom", "Admin")">Unallocate Classroom</a>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container body-content" style="margin-top: 80px;">
        @RenderBody()
        @*<hr />
        <footer style="position: inherit; bottom: 0; width: 100%; height: 30px; /* Height of the footer */">
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>*@
    </div>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/alertify.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.timepicker.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/2.3.4/jspdf.plugin.autotable.js"></script>*@
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/Master.js"></script>
</body>
</html>